[package]
name = "spring/spring-testing-place"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
react-roblox = "jsdotlua/react-roblox@17.2.1"
react = "jsdotlua/react@17.2.1"